version: '3.8'

services:
  # Backend Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: always

  # Frontend Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://task-manager-custom.onrender.com
    depends_on:
      - server
    restart: always
